// swift-tools-version: 6.0
import PackageDescription

// Firebase version this package mirrors. Bumped by Scripts/make-release.sh.
let firebaseVersion = "12.14.0"

// firebase-shell
//
// Consumes Google's precompiled, vendor-signed Firebase xcframeworks (the
// `Firebase.zip` manual distribution) as individual SwiftPM binary targets,
// re-hosted one zip per xcframework by Scripts/make-release.sh.
//
// Why this exists: building Firebase from source via firebase-ios-sdk made
// Tuist emit each GoogleUtilities sub-product as a standalone dynamic framework,
// which tripped App Store ITMS-91065 (missing vendor signature, which only
// ships in this precompiled distribution). Statically linking the source
// products instead stripped ObjC category methods (e.g. `gul_dataByGzippingData:`)
// and crashed at runtime. The precompiled xcframeworks are static AND signed by
// Google, so linking them sidesteps both problems.
//
// `FirebaseKit` wraps all of them in a single target. Consumers depend only on
// `FirebaseKit`, link it as ONE dynamic framework, and get every Firebase
// module via `@_exported import`. That keeps Firebase's global state (the
// `FirebaseApp` singleton, Crashlytics, etc.) in exactly one image, avoiding the
// duplicate-link/duplicate-singleton hazard of linking static libs into both a
// shared framework and the app.
//
// IMPORTANT linker flags: Google's README requires `-ObjC` and `-lc++`, and the
// dynamic wrapper additionally needs `-all_load` (or per-framework `-force_load`)
// so no Firebase symbol is dead-stripped out of FirebaseKit before consumers can
// reference it. These are applied by the CONSUMER (Riverside's Tuist/Package.swift
// via PackageSettings.targetSettings["FirebaseKit"]), not here, because SwiftPM
// `.unsafeFlags` would forbid using this package as a versioned dependency.
let package = Package(
    name: "firebase-shell",
    platforms: [
        .iOS(.v15),
        .macOS(.v11)
    ],
    products: [
        .library(name: "FirebaseKit", targets: ["FirebaseKit"])
    ],
    targets: [
        .target(
            name: "FirebaseKit",
            dependencies: [
                "FirebaseAnalytics",
                "FirebaseCore",
                "FirebaseCoreInternal",
                "FirebaseCoreExtension",
                "FirebaseInstallations",
                "FirebaseCrashlytics",
                "FirebaseSessions",
                "FirebaseMessaging",
                "FirebaseRemoteConfigInterop",
                "GoogleAppMeasurement",
                "GoogleAppMeasurementIdentitySupport",
                // iOS-only: GoogleAdsOnDeviceConversion ships no macOS slice, and
                // Google's README requires disabling it for Mac Catalyst. The
                // `.iOS` platform condition excludes both macOS and macCatalyst.
                .target(name: "GoogleAdsOnDeviceConversion", condition: .when(platforms: [.iOS])),
                "GoogleDataTransport",
                "GoogleUtilities",
                "nanopb",
                "FBLPromises",
                "Promises"
            ],
            path: "Sources/FirebaseKit"
        ),

        // BINARY_TARGETS_BEGIN
        // GENERATED by Scripts/make-release.sh for Firebase 12.14.0.
        // Do not edit by hand; re-run the script to bump versions.
        .binaryTarget(
            name: "FBLPromises",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FBLPromises.xcframework.zip",
            checksum: "2c5c8a4a4e7682c98d2762a9d1cb00083430216d61881ab691378c9ca2ecc67d"
        ),
        .binaryTarget(
            name: "FirebaseAnalytics",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseAnalytics.xcframework.zip",
            checksum: "48e602b5855e6c1cd2358ed48e87d28ae164ecabf6c50f5d66278b9b6ba18e83"
        ),
        .binaryTarget(
            name: "FirebaseCore",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCore.xcframework.zip",
            checksum: "58e1eca994cb5357cca1397a3a9ea5e2ad6cb9fab9c377c9f5aa30d54021f597"
        ),
        .binaryTarget(
            name: "FirebaseCoreInternal",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCoreInternal.xcframework.zip",
            checksum: "cc2eddfef5bf6f5d787cb700c5939830f06a3749ad98c22672b4bd640423921e"
        ),
        .binaryTarget(
            name: "FirebaseInstallations",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseInstallations.xcframework.zip",
            checksum: "3f9780059e5508546ce0c83308fe02c198dd1e7672f5a7b66bc6c7a455c76019"
        ),
        .binaryTarget(
            name: "GoogleAdsOnDeviceConversion",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAdsOnDeviceConversion.xcframework.zip",
            checksum: "e47013651eef23613bef967e071d68321e9215b906be1ac5feb7ac42ead4d344"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurement",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAppMeasurement.xcframework.zip",
            checksum: "e489c85bdae63f8114f107beeea0071a2f4af7c64fd8c81d63b521004d2d76ea"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurementIdentitySupport",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAppMeasurementIdentitySupport.xcframework.zip",
            checksum: "b6dc43e3ffe90da8ae204aad0beae6527ae0d14c38998055615c066e732b2e49"
        ),
        .binaryTarget(
            name: "GoogleUtilities",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleUtilities.xcframework.zip",
            checksum: "0ed0cb9f9f376d0e23e64604af7bde8350fc232d026bfe1fb7e69a4e6813ed30"
        ),
        .binaryTarget(
            name: "nanopb",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/nanopb.xcframework.zip",
            checksum: "168765712a9cac1abba3708b306218a0b4112d091e053854b3caf55437d3c047"
        ),
        .binaryTarget(
            name: "FirebaseCoreExtension",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCoreExtension.xcframework.zip",
            checksum: "0868554483715b00962444624919a6efc5b0974d95ffbb7110f108f76812731c"
        ),
        .binaryTarget(
            name: "FirebaseCrashlytics",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCrashlytics.xcframework.zip",
            checksum: "259ee54284ced2e967b03cc94ac5138de7e39b6cd69822407e1135fca331c2be"
        ),
        .binaryTarget(
            name: "FirebaseRemoteConfigInterop",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseRemoteConfigInterop.xcframework.zip",
            checksum: "f3f64a7318b10a14875ba513fe6b3bd0d2d4de5458f1587703adccb22c12d8b5"
        ),
        .binaryTarget(
            name: "FirebaseSessions",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseSessions.xcframework.zip",
            checksum: "a62a4ce2dce42773701de77450151ba11e8a57ff2ce0214bb5dacef870eb6f05"
        ),
        .binaryTarget(
            name: "GoogleDataTransport",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleDataTransport.xcframework.zip",
            checksum: "ac794fdeb718542cb3fe7689b6c7e2392f3511f7de7508e70c9ce962483039e3"
        ),
        .binaryTarget(
            name: "Promises",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/Promises.xcframework.zip",
            checksum: "23c241810f523ab7983b052ed8dda1b70e4e644f31ce8c409d004a45d116f50c"
        ),
        .binaryTarget(
            name: "FirebaseMessaging",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseMessaging.xcframework.zip",
            checksum: "70285d3ae90e6a19fbe4aed82d95f17da45136e41a99a24ce60bb423a20c0949"
        ),
        // BINARY_TARGETS_END
    ]
)
