// swift-tools-version: 6.0
import PackageDescription

// Firebase version this package mirrors. Bumped by Scripts/make-release.sh.
let firebaseVersion = "12.14.0"

// firebase-shell
//
// Consumes Google's precompiled, vendor-signed Firebase xcframeworks (the
// `Firebase.zip` manual distribution) as individual SwiftPM binary targets,
// re-hosted one zip per xcframework by Scripts/make-release.sh.
//
// Why this exists: building Firebase from source via firebase-ios-sdk made
// Tuist emit each GoogleUtilities sub-product as a standalone dynamic framework,
// which tripped App Store ITMS-91065 (missing vendor signature, which only
// ships in this precompiled distribution). Statically linking the source
// products instead stripped ObjC category methods (e.g. `gul_dataByGzippingData:`)
// and crashed at runtime. The precompiled xcframeworks are static AND signed by
// Google, so linking them sidesteps both problems.
//
// `FirebaseKit` wraps all of them in a single target. Consumers depend only on
// `FirebaseKit`, link it as ONE dynamic framework, and get every Firebase
// module via `@_exported import`. That keeps Firebase's global state (the
// `FirebaseApp` singleton, Crashlytics, etc.) in exactly one image, avoiding the
// duplicate-link/duplicate-singleton hazard of linking static libs into both a
// shared framework and the app.
//
// IMPORTANT linker flags: Google's README requires `-ObjC` and `-lc++`, and the
// dynamic wrapper additionally needs `-all_load` (or per-framework `-force_load`)
// so no Firebase symbol is dead-stripped out of FirebaseKit before consumers can
// reference it. These are applied by the CONSUMER (Riverside's Tuist/Package.swift
// via PackageSettings.targetSettings["FirebaseKit"]), not here, because SwiftPM
// `.unsafeFlags` would forbid using this package as a versioned dependency.
let package = Package(
    name: "firebase-shell",
    platforms: [
        .iOS(.v15),
        .macOS(.v11)
    ],
    products: [
        .library(name: "FirebaseKit", targets: ["FirebaseKit"])
    ],
    targets: [
        .target(
            name: "FirebaseKit",
            dependencies: [
                "FirebaseAnalytics",
                "FirebaseCore",
                "FirebaseCoreInternal",
                "FirebaseCoreExtension",
                "FirebaseInstallations",
                "FirebaseCrashlytics",
                "FirebaseSessions",
                "FirebaseMessaging",
                "FirebaseRemoteConfigInterop",
                "GoogleAppMeasurement",
                "GoogleAppMeasurementIdentitySupport",
                // iOS-only: GoogleAdsOnDeviceConversion ships no macOS slice, and
                // Google's README requires disabling it for Mac Catalyst. The
                // `.iOS` platform condition excludes both macOS and macCatalyst.
                .target(name: "GoogleAdsOnDeviceConversion", condition: .when(platforms: [.iOS])),
                "GoogleDataTransport",
                "GoogleUtilities",
                "nanopb",
                "FBLPromises",
                "Promises"
            ],
            path: "Sources/FirebaseKit"
        ),

        // BINARY_TARGETS_BEGIN
        // GENERATED by Scripts/make-release.sh for Firebase 12.14.0.
        // Do not edit by hand; re-run the script to bump versions.
        .binaryTarget(
            name: "FBLPromises",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FBLPromises.xcframework.zip",
            checksum: "b1926b79cfb0bafa20026315cd3dc925f4d49a705ed8909e4c2f662e0dadbd7b"
        ),
        .binaryTarget(
            name: "FirebaseAnalytics",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseAnalytics.xcframework.zip",
            checksum: "b9467c2fe5577b07f3a88d7ceba28b74f37607e27b87b62a03daf4a593bc1f16"
        ),
        .binaryTarget(
            name: "FirebaseCore",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCore.xcframework.zip",
            checksum: "c13a9e8f89e56c2c4d7e0ce08c7bf0a0b60edaca63628bcdf9bf4fc2541c71a8"
        ),
        .binaryTarget(
            name: "FirebaseCoreInternal",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCoreInternal.xcframework.zip",
            checksum: "c52345f9010966ad3ec733ae16ac42429d28b24e1e5377d6c0c67379d0a963f6"
        ),
        .binaryTarget(
            name: "FirebaseInstallations",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseInstallations.xcframework.zip",
            checksum: "c9cea6147d57ab0870d82f79bfb4949daa64c9636ae3793de580fbc8da21725e"
        ),
        .binaryTarget(
            name: "GoogleAdsOnDeviceConversion",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAdsOnDeviceConversion.xcframework.zip",
            checksum: "e47013651eef23613bef967e071d68321e9215b906be1ac5feb7ac42ead4d344"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurement",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAppMeasurement.xcframework.zip",
            checksum: "76bd1c98c3d9188e8fbe587835596e7d93b96106553b15d4a9f50cf50e8ef5c4"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurementIdentitySupport",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAppMeasurementIdentitySupport.xcframework.zip",
            checksum: "138305e9123f9a702af40063aa2912540f4d77896b7498a891837217b8cdeb54"
        ),
        .binaryTarget(
            name: "GoogleUtilities",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleUtilities.xcframework.zip",
            checksum: "c42ef14a7a6f3ca612f9d49c96f5a21fe0ba242befae6e0683b7d70d54ed5d37"
        ),
        .binaryTarget(
            name: "nanopb",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/nanopb.xcframework.zip",
            checksum: "7c5ca0b698920c061afbf40e911f7e7be77ca2be7c3944dd3460a39d34ba90ff"
        ),
        .binaryTarget(
            name: "FirebaseCoreExtension",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCoreExtension.xcframework.zip",
            checksum: "33dcc23368c379e512fa711580709e2b46ea811ca1a00a251a6eb054548363e1"
        ),
        .binaryTarget(
            name: "FirebaseCrashlytics",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCrashlytics.xcframework.zip",
            checksum: "e340b356815cef0788967a57d1470654a391d35778d4fc4a11e6a36c264abb70"
        ),
        .binaryTarget(
            name: "FirebaseRemoteConfigInterop",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseRemoteConfigInterop.xcframework.zip",
            checksum: "73667823b1b1222d812e3da6e1429472b5e61c96d1184a9c1c5581ad0a5a4ee3"
        ),
        .binaryTarget(
            name: "FirebaseSessions",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseSessions.xcframework.zip",
            checksum: "c28d1e65e1f1d435a5fe62abc1dde6134e4988f1b54d605f3f7ea798c46f42fa"
        ),
        .binaryTarget(
            name: "GoogleDataTransport",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleDataTransport.xcframework.zip",
            checksum: "7b3df8f7e3dd3c2c046001855805ddfe59098e1f7ecfa925e437cb51e2447c5b"
        ),
        .binaryTarget(
            name: "Promises",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/Promises.xcframework.zip",
            checksum: "4dd336ee4975d2b89761af2e2ef9dba1c336b7d642317fe432c4b8c3cbdfd55c"
        ),
        .binaryTarget(
            name: "FirebaseMessaging",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseMessaging.xcframework.zip",
            checksum: "4f6dac102a69204e4bdffd35cdcfbf181621191bf4b1b8c99215287e4145aea5"
        ),
        // BINARY_TARGETS_END
    ]
)
