// swift-tools-version: 6.0
import PackageDescription

// Firebase version this package mirrors. Bumped by Scripts/make-release.sh.
let firebaseVersion = "12.14.0"

// firebase-shell
//
// Consumes Google's precompiled, vendor-signed Firebase xcframeworks (the
// `Firebase.zip` manual distribution) as individual SwiftPM binary targets,
// re-hosted one zip per xcframework by Scripts/make-release.sh.
//
// Why this exists: building Firebase from source via firebase-ios-sdk made
// Tuist emit each GoogleUtilities sub-product as a standalone dynamic framework,
// which tripped App Store ITMS-91065 (missing vendor signature, which only
// ships in this precompiled distribution). Statically linking the source
// products instead stripped ObjC category methods (e.g. `gul_dataByGzippingData:`)
// and crashed at runtime. The precompiled xcframeworks are static AND signed by
// Google, so linking them sidesteps both problems.
//
// `FirebaseKit` wraps all of them in a single target. Consumers depend only on
// `FirebaseKit`, link it as ONE dynamic framework, and get every Firebase
// module via `@_exported import`. That keeps Firebase's global state (the
// `FirebaseApp` singleton, Crashlytics, etc.) in exactly one image, avoiding the
// duplicate-link/duplicate-singleton hazard of linking static libs into both a
// shared framework and the app.
//
// IMPORTANT linker flags: Google's README requires `-ObjC` and `-lc++`, and the
// dynamic wrapper additionally needs `-all_load` (or per-framework `-force_load`)
// so no Firebase symbol is dead-stripped out of FirebaseKit before consumers can
// reference it. These are applied by the CONSUMER (Riverside's Tuist/Package.swift
// via PackageSettings.targetSettings["FirebaseKit"]), not here, because SwiftPM
// `.unsafeFlags` would forbid using this package as a versioned dependency.
let package = Package(
    name: "firebase-shell",
    platforms: [
        .iOS(.v15),
        .macOS(.v11)
    ],
    products: [
        .library(name: "FirebaseKit", targets: ["FirebaseKit"])
    ],
    targets: [
        .target(
            name: "FirebaseKit",
            dependencies: [
                "FirebaseAnalytics",
                "FirebaseCore",
                "FirebaseCoreInternal",
                "FirebaseCoreExtension",
                "FirebaseInstallations",
                "FirebaseCrashlytics",
                "FirebaseSessions",
                "FirebaseMessaging",
                "FirebaseRemoteConfigInterop",
                "GoogleAppMeasurement",
                "GoogleAppMeasurementIdentitySupport",
                // iOS-only: GoogleAdsOnDeviceConversion ships no macOS slice, and
                // Google's README requires disabling it for Mac Catalyst. The
                // `.iOS` platform condition excludes both macOS and macCatalyst.
                .target(name: "GoogleAdsOnDeviceConversion", condition: .when(platforms: [.iOS])),
                "GoogleDataTransport",
                "GoogleUtilities",
                "nanopb",
                "FBLPromises",
                "Promises"
            ],
            path: "Sources/FirebaseKit"
        ),

        // BINARY_TARGETS_BEGIN
        // GENERATED by Scripts/make-release.sh for Firebase 12.14.0.
        // Do not edit by hand; re-run the script to bump versions.
        .binaryTarget(
            name: "FBLPromises",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FBLPromises.xcframework.zip",
            checksum: "61fc5d088b8c989da5700a7e2981306d75be51741d808cb4a194d16ea2e3401c"
        ),
        .binaryTarget(
            name: "FirebaseAnalytics",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseAnalytics.xcframework.zip",
            checksum: "8ea37874a43f041da0d4bedae42005d362378d439aafca4fda1f8be3647dcfde"
        ),
        .binaryTarget(
            name: "FirebaseCore",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCore.xcframework.zip",
            checksum: "b18e88a7a0907a5e57291256bb986c6934ca8f41b6e339eea6c131c5a755689a"
        ),
        .binaryTarget(
            name: "FirebaseCoreInternal",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCoreInternal.xcframework.zip",
            checksum: "8a179511241251f504e3b3c44f197287c37643861efe2a78221acdf2343b36ac"
        ),
        .binaryTarget(
            name: "FirebaseInstallations",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseInstallations.xcframework.zip",
            checksum: "5d7d7f84ae9e3a62d35c2611d0fd3541590c290f29a957bae061f8bb7380d0f8"
        ),
        .binaryTarget(
            name: "GoogleAdsOnDeviceConversion",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAdsOnDeviceConversion.xcframework.zip",
            checksum: "0121bc7b43671256a2fb3fc0a50642cd16d35de6c3cc2b73551f1be3d8a22ac1"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurement",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAppMeasurement.xcframework.zip",
            checksum: "61731bd1f860adafc924eec5eab60736cd9fd4d48694fc8b84be8b266c4dcd3e"
        ),
        .binaryTarget(
            name: "GoogleAppMeasurementIdentitySupport",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleAppMeasurementIdentitySupport.xcframework.zip",
            checksum: "03229fe9ad5451a28503d01f89f5e08a40f75c376ab0b598b1be5505101a7f4b"
        ),
        .binaryTarget(
            name: "GoogleUtilities",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleUtilities.xcframework.zip",
            checksum: "b1ca07602dac7b9f89f7b289051d559ca78fbd9e625bc040e2202138df19276d"
        ),
        .binaryTarget(
            name: "nanopb",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/nanopb.xcframework.zip",
            checksum: "a6ee37a15b06c35baa3618f33ca2210803dca144c990a887f0ac92d3a0163051"
        ),
        .binaryTarget(
            name: "FirebaseCoreExtension",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCoreExtension.xcframework.zip",
            checksum: "f34a1250e4296e8f347ae2b25e7f72e6159d3db10b58edf43b1f23b1b372f0e1"
        ),
        .binaryTarget(
            name: "FirebaseCrashlytics",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseCrashlytics.xcframework.zip",
            checksum: "0465fdde03c94efda122ef4e1aa20cfb3bb7757ce55dcddd9549ed01e5fce6de"
        ),
        .binaryTarget(
            name: "FirebaseRemoteConfigInterop",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseRemoteConfigInterop.xcframework.zip",
            checksum: "fbde6c3bdecf38f733a3ea0981eb66ab5b6918af8a7a7a6b5154f17a4f3dc91d"
        ),
        .binaryTarget(
            name: "FirebaseSessions",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseSessions.xcframework.zip",
            checksum: "6fdc04a73ba1ed469b0d1a28afcbd532759ff2a635d7dbca82fd5bef2cfcc840"
        ),
        .binaryTarget(
            name: "GoogleDataTransport",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/GoogleDataTransport.xcframework.zip",
            checksum: "19e66bf5e592eb8aabe1c6b73373fb779bf42e29b385e27a60bd07358bb380d1"
        ),
        .binaryTarget(
            name: "Promises",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/Promises.xcframework.zip",
            checksum: "37c6db8f5ea7859ccc1dcdcfe43a51535c0d8c62e1a350abf00a0a284c98bcf0"
        ),
        .binaryTarget(
            name: "FirebaseMessaging",
            url: "https://github.com/natanrolnik/firebase-shell/releases/download/12.14.0/FirebaseMessaging.xcframework.zip",
            checksum: "07058d98ca5b67b442dbb8ad9edca37fe8bb4f6b72452338166c35b72b5ba89d"
        ),
        // BINARY_TARGETS_END
    ]
)
